version: '3.8'

services:
  php:
    build:
      context: ./php
    volumes:
      - ./src:/var/www/html
    expose:
      - 9000

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php